# Enables QMK's RGB code
RGBLIGHT_ENABLE = yes
RGBLIGHT_EFFECT_SNAKE = yes
RGBLIGHT_EFFECT_SNAKE = 0

MOUSEKEY_ENABLE = yes

COMBO_ENABLE = yes

# Audio control and System control
EXTRAKEY_ENABLE = yes

KEY_OVERRIDE_ENABLE = yes

